#!/usr/bin/env bash

if ! [[ $(command -v "clang-format") ]]; then
  echo "Commit cannot proceed. clang-format is not installed."
  exit 1
fi

format_file() {
  fullfile="${1}"

  if [ -f $fullfile ]; then

    filename=$(basename -- "$fullfile")
    extension="${filename##*.}"

    if [ $extension = "h" ] || [ $extension = "cpp" ]; then
      clang-format -i ${1}
      git add ${1}
    fi
  fi
}

case "${1}" in
  --about )
    echo "Runs clang-format on source files"
    ;;
  * )
    for file in `git diff-index --cached --name-only HEAD` ; do
      format_file "${file}"
    done
    ;;
esac
