#!/usr/bin/env bash
#
# Automatically clang-formats files when commiting them.
# To use, from the top level of the repo, run:
#   cp tools/clang-format-pre-commit .git/hooks/pre-commit 

CLANG_FORMAT_EXE="clang-format"

if [[ "${1}" = "-h" ]] || [[ "${1}" = "--help" ]]; then
  >&2 echo "Runs clang-format on source files changed in commit"
  exit 1
fi

if ! [[ $(command -v "${CLANG_FORMAT_EXE}") ]]; then
  >&2 echo "Warning: clang-format is not installed. Autoformatting not supported. (from git pre-commit hook)"
  exit 0
fi

for FILE in $(git diff-index --cached --name-only HEAD) ; do
  if [ -f ${FILE} ]; then
    WITHOUT_PATH=$(basename -- "${FILE}")
    EXTENSION="${WITHOUT_PATH##*.}"

    if [[ "${EXTENSION}" = "h" ]] || [[ "${EXTENSION}" = "cpp" ]] || [[ "${EXTENSION}" = "c" ]]; then
      "${CLANG_FORMAT_EXE}" -i "${FILE}"
      git add "${FILE}"
    fi
  fi
done

