[package]
name = "disc_golf_flight_simulation"
version = "0.1.0"
edition = "2021"
authors = [ "Jeremy Sigrist" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-glm = "0.17.0"

